# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 3e5f56f4bda46b6d453d41bda5c54f6d5c72dcd77e37f36fdec3d26d15d56caf26742b070d1405c934b5d7ab32ee029dc3fb37babf682656ce3e23b8ddba913e

test:
  secret_key_base: 908016c30d6099b7b64e05f7a34061f9e9bde50ca70ecf0ada1fc16e823d2aea47a509944b59dd890b8ac23e21a06a5c2e413eae15f80f2b48060601eaae8e00

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
